name: Deno CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Start server
        run: deno run --allow-net --allow-read --allow-write --unstable src/index.ts &
      - name: Run tests
        run: deno test --allow-net --allow-read --allow-write --unstable
